---
title: "R Notebook"
output: html_notebook
---

# Intro

inputs: (1) resp (in intermediate folder) (2) e (in intermediate folder)
workflow: 
outputs: v

# Libraries
```{r}
library(dplyr)
library(rgdal)
library(raster)
library(qdapTools)
library(RPostgreSQL)
```


# Inputs
```{r}

e <- read.csv(file.path(savepath, "e.csv"))

resp <- read.csv(file.path(savepath, paste(vme,"resp.csv", collapse=" ")))

# set vme (again!)
vme <- "Hard bottom sponge aggregations"
```


# Aggregate to whole video line and calculate sd
```{r}
respw <- resp %>% mutate(video.line=sub("_.*", "", SampID))

respw <- respw %>% group_by(video.line) %>%
  summarize(mean_rich = mean(tot_rich), mean_dens = mean(tot_dens), sd_dens = sd(tot_dens))

head(respw)
```

# Make spatial object
```{r}
resp_spat1 <- resp %>% mutate(mean_long=as.numeric(pull(
                                dplyr::filter(data.frame(lookup(SampID,dplyr::select(sample_info, c(SampID, mean.longitude)), missing = NULL)), 
                                                      !duplicated(data.frame(qdapTools::lookup(SampID,dplyr::select(sample_info, c(SampID, mean.longitude)), missing = NULL)))
                                                       ))),
                             mean_lat=as.numeric(pull(
                               dplyr::filter(data.frame(lookup(SampID,dplyr::select(sample_info, c(SampID, mean.latitude)), missing = NULL)), 
                                                      !duplicated(data.frame(qdapTools::lookup(SampID,dplyr::select(sample_info, c(SampID, mean.latitude)), missing = NULL)))
                                                       )))) %>%
            filter(!is.na(mean_long))

resp_spat <- SpatialPointsDataFrame(dplyr::select(resp_spat1, c(mean_long, mean_lat)), dplyr::select(resp_spat1, c(SampID,tot_rich, tot_dens, vmeind_density)))  
                      #%>% utmize

writeOGR(resp_spat, savepath, paste(vme, "resp_spat"), driver = "ESRI Shapefile", overwrite_layer = TRUE)

# make resp have the same number of rows as resp_spat:

resp <- resp %>% filter(SampID%in%resp_spat@data$SampID)
```

# Get coordinates of video lines
```{r}
library(RPostgreSQL)
library(rgdal)

postgres_driver <- dbDriver("PostgreSQL")
postgres_conn <- dbConnect(postgres_driver,
                           dbname = "marbunn",
                           host = "postgres.hi.no",
                           port = 5432,
                           user = "marbunn_read",
                           password = "Ecac7adgb!")
tab_station <- dbGetQuery(postgres_conn, "select * from tab_station")
tab_station <- tab_station[which(tab_station$equipment==2),]

```

# Make spatial object, video line level
```{r}

resp_spat1 <- respw %>% mutate(mean_long=as.numeric(pull(
  dplyr::filter(data.frame(lookup(video.line,dplyr::select(tab_station, c(sample_no, lon_mid_dec)), missing = NULL))))),
  mean_lat=as.numeric(pull(
    dplyr::filter(data.frame(lookup(video.line,dplyr::select(tab_station, c(sample_no, lat_mid_dec)), missing = NULL)))))) %>%
  dplyr::filter(!is.na(mean_long)) %>% rename(vmeind_density = mean_dens)

coords <- coordinates(dplyr::select(resp_spat1, c(mean_long, mean_lat)))

resp_spat_vl <- SpatialPointsDataFrame(coords, dplyr::select(resp_spat1, c(video.line,mean_rich, vmeind_density, sd_dens))) %>%
                       utmize

writeOGR(resp_spat_vl, savepath, paste(vme, "resp_spat_vl"), driver = "ESRI Shapefile", overwrite_layer = TRUE)

# make resp have the same number of rows as resp_spat:

respw <- respw %>% filter(video.line%in%resp_spat@data$video.line)
```


# join predictor values, response values, and standard deviation values
```{r}
v <- left_join(dplyr::select(resp, SampID),data.frame(e), by="SampID")
# generate random data if needed
v
```

# Save outputs
```{r}
rm(resp_spat1)
write.csv(v, file.path(savepath, "v.csv"), row.names = FALSE)
```
