---
title: "R Notebook"
output: html_notebook
---
# Intro
inputs: e (from intermediate folder), new resp (from intermediate folder), standard variation of vme density (from intermediate folder)
output: clean v table

# Inputs
```{r}
e <- read.csv(file.path(savepath, "pred_data/e.csv"))
resp <- read.csv(file.path(savepath, paste(vme,"minus", paste(substr(remove, 1,7), collapse=", "),"resp new.csv", collapse=" ")))
stdev <- read.csv(file.path(savepath, paste(vme,"minus", paste(substr(remove, 1,7), collapse=", "),"st_dev_vme_dens.csv")))
```

# join predictor values, response values, and standard deviation values
```{r}
e <- cbind(e,sample_info)
v <- left_join(resp,data.frame(e), by="SampID")
dim(v)
```
# join standard deviation of vme density
```{r}
v <- v %>% left_join(stdev, by="video.line")
```

# save
```{r}
write.csv(dplyr::select(v,
                        SampID,
                        tot_rich,
                        tot_dens,
                        vmeind_density,
                        mean_dens,
                        mean_rich,
                        sd_dens,
                        bathy,
                        BO22_carbonphytoltmax_bdmean,
                        BO22_carbonphytoltmax_ss,
                        BO22_carbonphytoltmin_bdmean,
                        BO22_carbonphytoltmin_ss,
                        BO22_carbonphytomean_bdmean,
                        BO22_carbonphytomean_ss,
                        BO22_carbonphytorange_bdmean,
                        BO22_carbonphytorange_ss,    
                        BO22_chloltmin_bdmean,    
                        BO22_chlomean_ss,    
                        BO22_dissoxltmax_bdmean,    
                        BO22_dissoxrange_bdmean,    
                        BO22_icecovermean_ss,    
                        BO22_icethickltmin_ss,    
                        BO22_ironltmax_bdmean,    
                        BO22_ironrange_bdmean,    
                        BO22_lightbotmean_bdmean,    
                        BO22_nitrateltmin_bdmean,    
                        BO22_phosphateltmax_bdmean,    
                        BO22_phosphaterange_bdmean,    
                        BO22_ppltmin_bdmean,    
                        BO22_ppmean_ss,    
                        BO22_silicateltmax_bdmean,    
                        BO22_silicaterange_bdmean,    
                        BO22_chloltmax_bdmean,
                        BO22_chloltmax_ss,
                        BO22_chloltmin_ss,
                        BO22_chlomean_bdmean,
                        BO22_chlorange_bdmean,
                        BO22_chlorange_ss,
                        BO22_dissoxltmin_bdmean,
                        BO22_dissoxmean_bdmean,
                        BO22_icecoverltmax_ss,
                        BO22_icecoverltmin_ss,
                        BO22_icecoverrange_ss,
                        BO22_icethickltmax_ss,
                        BO22_icethickmean_ss,
                        BO22_icethickrange_ss,
                        BO22_ironltmin_bdmean,
                        BO22_ironmean_bdmean,
                        BO22_lightbotltmax_bdmean,
                        BO22_lightbotltmin_bdmean,
                        BO22_lightbotrange_bdmean,
                        BO22_nitrateltmax_bdmean,
                        BO22_nitratemean_bdmean,
                        BO22_nitraterange_bdmean,
                        BO22_phosphateltmin_bdmean,
                        BO22_phosphatemean_bdmean,
                        BO22_ppltmax_bdmean,
                        BO22_ppltmax_ss,
                        BO22_ppltmin_ss,
                        BO22_ppmean_bdmean,
                        BO22_pprange_bdmean,
                        BO22_pprange_ss,
                        BO22_silicateltmin_bdmean,
                        BO22_silicatemean_bdmean,
                        CDirmax_Robinson,
                        CDirmean_Robinson,
                        CDirmin_Robinson,    
                        CDirsd_Robinson,
                        CSpdmax_Robinson,    
                        CSpdmean_Robinson,
                        CSpdmin_Robinson,
                        CSpdsd_Robinson,    
                        MLDmax_Robinson,
                        MLDmean_Robinson,    
                        MLDmin_Robinson,
                        MLDsd_Robinson,
                        MS_biogeo05_dist_shore_5m,
                        Smax_Robinson,    
                        Smean_Robinson,
                        Smin_Robinson,
                        Ssd_Robinson,
                        Tmax_Robinson,                  
                        Tmean_Robinson,
                        Tmin_Robinson,
                        Tsd_Robinson,                  
                        Umax_Robinson,
                        Umean_Robinson,
                        Umin_Robinson,                  
                        Usd_Robinson,
                        Vmax_Robinson,                  
                        Vmean_Robinson,
                        Vmin_Robinson,
                        Vsd_Robinson,
                        cobB,
                        diffME3,
                        diffME9,
                        gravel,    
                        landscape,
                        msr1_mag,    
                        msr5_mag,
                        mud,    
                        rock,
                        salt_max,
                        salt_mean,    
                        salt_min,
                        salt_std,
                        sand,    
                        sedclass,
                        seddan,
                        sedmil,    
                        slope3,
                        slope9,
                        spd_max,                  
                        spd_mean,
                        spd_min,
                        spd_std,                  
                        temp_max,
                        temp_mean,                  
                        temp_min,
                        temp_std,
                        u_bott_mean,
                        v_bott_mean		    
			   ), file.path(savepath, paste(vme, "minus", paste(substr(remove, 1,7), collapse=", "), "v.csv", collapse=" ")), row.names = FALSE)
```
